### ISSUE TITLE
compile_model import 

### ISSUE THREAD

**Issue by aileenliao03** [justincdavis/oakutils#56]
I am trying to run the examples/blobs/compile_model.py script. I get an error: 
    from oakutils.blobs import compile_model
ImportError: cannot import name 'compile_model' from 'oakutils.blobs' (/home/user/miniconda3/envs/new_oak/lib/python3.11/site-packages/oakutils/blobs/__init__.py)

I tried 
import oakutils.blobs._compiler as compiler
print(dir(compiler))
 
and 
import oakutils.blobs as blobs
print(dir(blobs))

to visualize but get an error or do not see the compile_model function

**Comment by justincdavis** [comment]
Have you installed oakutils with the compiler dependencies? 

If not I would run `pip install --upgrade oakutils[compiler]`

Since compiling blobs directly from PyTorch models has a lot of extra packages which are not needed for the other functionalities, their installation is separated into another tag. 

Let me know if that solves your issue!

**Comment by aileenliao03** [comment]
Oops yes, this solves it. Thanks!
